"""
Calculate skill metrics for paired one-dimensional time series.

This module takes pandas dataframes generated by get_skill.py and calculates
skill assessment metrics. The output is a list with the result for each metric.
"""

import math
import os
import warnings
from logging import Logger
from typing import Any, Union

import numpy as np
import pandas as pd
from scipy.stats import ConstantInputWarning

from ofs_skill.obs_retrieval.get_station_tidal_data import get_station_tidal_data
from ofs_skill.skill_assessment import nos_metrics
from ofs_skill.skill_assessment.format_paired_one_d import get_distance_angle

warnings.simplefilter('ignore', ConstantInputWarning)


def skill_scalar(
    df_paired: pd.DataFrame,
    name_var: str,
    station_id: str,
    prop: Any,
    logger: Logger,
) -> list[Union[float, str]]:
    """
    Calculate skill metrics for scalar variables.

    Computes skill assessment metrics including RMSE, correlation coefficient,
    bias, central frequency, and outlier frequencies for scalar variables
    (water level, temperature, salinity).

    Parameters
    ----------
    df_paired : pd.DataFrame
        Paired observation and model data with columns ['OBS', 'OFS', 'BIAS']
    name_var : str
        Variable name ('wl', 'temp', or 'salt')
    prop : Any
        Properties object containing configuration parameters
    logger : Logger
        Logger instance for logging messages

    Returns
    -------
    List[Union[float, str]]
        List of skill metrics:
        [rmse, r_value, bias, bias_perc, np.nan, cf, cfpf, pof, pofpf,
         nof, nofpf, stdev, X1]
        Where:
        - rmse: Root mean squared error
        - r_value: Pearson correlation coefficient
        - bias: Mean bias
        - bias_perc: Mean bias as percentage of mean observation
        - cf: Central frequency (percentage within error threshold)
        - cfpf: Central frequency pass/fail ('pass' if >= 90%)
        - pof: Positive outlier frequency
        - pofpf: Positive outlier frequency pass/fail
        - nof: Negative outlier frequency
        - nofpf: Negative outlier frequency pass/fail
        - mdpo: Max duration of positive outliers
        - mdpopf: MDPO pass/fail
        - mdno: Max duration of negative outliers
        - mdnopf: MDNO pass/fail
        - wof: worst-case outlier frequency
        - wofpf: WOF pass/fail
        - stdev: Standard deviation of bias
        - X1: Error threshold

    Notes
    -----
    Some stations have constant values for the entire period. By definition,
    correlation cannot be calculated between observations and model if one
    of the timeseries is constant, which will trigger a warning.
    """
    datathreshold = 5

    # Get target error range
    X1, X2 = nos_metrics.get_error_threshold(
        name_var, os.path.join(prop.path, 'conf', 'error_ranges.csv'))

    df_paired = df_paired.dropna(subset=['OBS', 'OFS'])
    # Update obs and ofs after handling NaN
    obs = df_paired['OBS']
    ofs = df_paired['OFS']
    df_bias = df_paired['BIAS']

    if np.nansum(~np.isnan(obs)) >= datathreshold:
        # RMSE -- fixed 8/13/24
        rmse = nos_metrics.rmse(ofs, obs)
        rmse = np.around(rmse, decimals=2)

        # Pearson's R
        r_value = nos_metrics.pearson_r(ofs, obs)
        if math.isnan(r_value):
            logger.warning(
                '%s -- The correlation coefficient could not be calculated (i.e. R=NaN)', name_var)
        r_value = np.around(r_value, decimals=2)

        # Mean bias & bias percent
        bias = df_bias.mean()  # Series mean from fortran SA
        bias = np.around(bias, decimals=2)
        bias_perc = 100 * (bias / obs.mean())
        bias_perc = np.around(bias_perc, decimals=2)

        # Central frequency
        # Not using X2 right now, only X1
        npbias = np.array(df_bias)
        cf = nos_metrics.central_frequency(npbias, X1)
        cf = np.around(cf, decimals=2)

        # Positive/negative outlier frequency
        pof = nos_metrics.positive_outlier_freq(npbias, X1)
        pof = np.around(pof, decimals=2)
        nof = nos_metrics.negative_outlier_freq(npbias, X1)
        nof = np.around(nof, decimals=2)

        # Standard deviation or error/bias
        stdev = nos_metrics.standard_deviation(npbias)
        stdev = np.around(stdev, decimals=2)

        # MDPO/MDNO
        mdpo = nos_metrics.max_duration_positive_outliers(npbias, X1)
        mdno = nos_metrics.max_duration_negative_outliers(npbias, X1)
        dt = np.asarray(df_paired['DateTime'].diff().dt.total_seconds() / 3600)[1]
        mdpo = mdpo * dt
        mdno = mdno * dt
        mdno = np.around(mdno, decimals=2)
        mdpo = np.around(mdpo, decimals=2)

        # Worst case outlier frequency (WOF)
        wof = None
        tidal_data = None
        if name_var == 'wl':
            # tidal_info contains the 'used_datum' that successfully returned data
            tidal_data, tidal_info = get_station_tidal_data(
                df_paired['DateTime'].min().to_pydatetime(),
                df_paired['DateTime'].max().to_pydatetime(),
                prop, station_id, logger
            )

            # Skip WOF if retrieved datum differs from requested model datum
            # This prevents bias in crossing logic caused by vertical reference offsets
            if tidal_data is not None and tidal_info.get('used_datum') == prop.datum:
                tides = pd.merge(df_paired, tidal_data, on='DateTime').reset_index()
                wof = nos_metrics.worst_case_outlier_frequency(
                    tides['OFS'],
                    tides['OBS'],
                    tides['TIDE'],
                    X1
                )
                wof = np.around(wof, decimals=2)
            elif tidal_data is not None:
                logger.warning(
                    'Skipping WOF for station %s: Tidal datum (%s) does not match requested datum (%s).',
                    station_id, tidal_info.get('used_datum'), prop.datum
                )

        # Check criteria
        # Pass or fail?
        criteria = nos_metrics.check_nos_criteria(cf, pof, nof, mdpo, mdno, wof)
        cfpf = criteria['cf']
        pofpf = criteria['pof']
        nofpf = criteria['nof']
        mdpopf = criteria['mdpo']
        mdnopf = criteria['mdno']
        wofpf = criteria['wof']

    else:
        nodatatext = '<' + str(datathreshold) + ' data points'
        rmse = nodatatext
        r_value = nodatatext
        bias = nodatatext
        bias_perc = nodatatext
        cf = nodatatext
        cfpf = nodatatext
        pof = nodatatext
        pofpf = nodatatext
        nof = nodatatext
        nofpf = nodatatext
        mdpo = nodatatext
        mdno = nodatatext
        mdpopf = nodatatext
        mdnopf = nodatatext
        wof = nodatatext
        wofpf = nodatatext
        stdev = nodatatext

    # Return stats
    return [rmse,
            r_value,
            bias,
            bias_perc,
            np.nan,
            cf,
            cfpf,
            pof,
            pofpf,
            nof,
            nofpf,
            mdpo,
            mdpopf,
            mdno,
            mdnopf,
            wof,
            wofpf,
            stdev,
            X1]


def skill_vector(
    df_paired: pd.DataFrame,
    name_var: str,
    prop: Any,
    logger: Logger,
) -> list[Union[float, str]]:
    """
    Calculate skill metrics for vector variables.

    Computes skill assessment metrics including RMSE, correlation coefficient,
    speed bias, direction bias, central frequency, and outlier frequencies for
    vector variables (currents).

    Parameters
    ----------
    df_paired : pd.DataFrame
        Paired observation and model data with columns ['OBS', 'OFS',
        'SPD_BIAS', 'DIR_BIAS']
    name_var : str
        Variable name ('cu' for currents)
    prop : Any
        Properties object containing configuration parameters
    logger : Logger
        Logger instance for logging messages

    Returns
    -------
    List[Union[float, str]]
        List of skill metrics:
        [rmse, r_value, bias, bias_perc, bias_dir, cf, cfpf, pof, pofpf,
         nof, nofpf, stdev, X1]
        Where:
        - rmse: Root mean squared error of speed
        - r_value: Pearson correlation coefficient of speed
        - bias: Mean speed bias
        - bias_perc: Mean speed bias as percentage
        - bias_dir: Mean direction bias
        - cf: Central frequency (percentage within error threshold)
        - cfpf: Central frequency pass/fail ('pass' if >= 90%)
        - pof: Positive outlier frequency
        - pofpf: Positive outlier frequency pass/fail
        - nof: Negative outlier frequency
        - nofpf: Negative outlier frequency pass/fail
        - stdev: Standard deviation of speed bias
        - X1: Error threshold
    """
    datathreshold = 5

    # Get target error range
    X1, X2 = nos_metrics.get_error_threshold(
        name_var, os.path.join(prop.path, 'conf', 'error_ranges.csv'))

    df_paired = df_paired.dropna(subset=['OBS', 'OFS'])
    # Update obs and ofs after handling NaN
    obs = df_paired['OBS']
    ofs = df_paired['OFS']
    spd_bias = df_paired['SPD_BIAS']
    dir_bias = df_paired['DIR_BIAS']
    if np.nansum(~np.isnan(obs)) >= datathreshold:
        # RMSE -- fixed 8/13/24
        rmse = nos_metrics.rmse(ofs, obs)
        rmse = np.around(rmse, decimals=2)

        # Pearson's R
        r_value = nos_metrics.pearson_r(ofs, obs)
        if math.isnan(r_value):
            logger.warning(
                '%s -- The correlation coefficient could not be calculated (i.e. R=NaN)',
                name_var)
        r_value = np.around(r_value, decimals=2)

        # Mean bias & bias percent
        bias = spd_bias.mean()
        bias_perc = 100 * (bias / obs.mean())
        bias = np.around(bias, decimals=2)
        bias_perc = np.around(bias_perc, decimals=2)
        bias_dir = dir_bias.mean()
        bias_dir = np.around(bias_dir, decimals=2)

        ######### SPEED THRESHOLD STATS ##########
        # Central frequency
        # Not using X2 right now, only X1
        npbias = np.array(spd_bias)
        cf = nos_metrics.central_frequency(npbias, X1)
        cf = np.around(cf, decimals=2)

        # Positive/negative outlier frequency
        pof = nos_metrics.positive_outlier_freq(npbias, X1)
        pof = np.around(pof, decimals=2)
        nof = nos_metrics.negative_outlier_freq(npbias, X1)
        nof = np.around(nof, decimals=2)

        # MDPO/MDNO
        mdpo = nos_metrics.max_duration_positive_outliers(npbias, X1)
        mdno = nos_metrics.max_duration_negative_outliers(npbias, X1)
        dt = np.asarray(df_paired['DateTime'].diff().dt.total_seconds() / 3600)[1]
        mdpo = mdpo * dt
        mdno = mdno * dt
        mdno = np.around(mdno, decimals=2)
        mdpo = np.around(mdpo, decimals=2)

        # Standard deviation or error/bias
        stdev = nos_metrics.standard_deviation(npbias)
        stdev = np.around(stdev, decimals=2)

        # Check criteria
        # Pass or fail?
        wof = None
        criteria = nos_metrics.check_nos_criteria(cf, pof, nof, mdpo, mdno, wof)
        cfpf = criteria['cf']
        pofpf = criteria['pof']
        nofpf = criteria['nof']
        mdpopf = criteria['mdpo']
        mdnopf = criteria['mdno']
        wofpf = criteria['wof']
    else:
        nodatatext = '<' + str(datathreshold) + ' data points'
        rmse = nodatatext
        r_value = nodatatext
        bias = nodatatext
        bias_perc = nodatatext
        bias_dir = nodatatext
        cf = nodatatext
        cfpf = nodatatext
        pof = nodatatext
        pofpf = nodatatext
        nof = nodatatext
        nofpf = nodatatext
        mdpo = nodatatext
        mdno = nodatatext
        mdpopf = nodatatext
        mdnopf = nodatatext
        wof = nodatatext
        wofpf = nodatatext
        stdev = nodatatext

    return [rmse,
            r_value,
            bias,
            bias_perc,
            bias_dir,
            cf,
            cfpf,
            pof,
            pofpf,
            nof,
            nofpf,
            mdpo,
            mdpopf,
            mdno,
            mdnopf,
            wof,
            wofpf,
            stdev,
            X1]

def skill_vector_dir(
    df_paired: pd.DataFrame,
    name_var: str,
    prop: Any,
    logger: Logger,
) -> list[Union[float, str]]:
    """
    Calculate skill metrics for vector variables.

    Computes skill assessment metrics including RMSE, correlation coefficient,
    speed bias, direction bias, central frequency, and outlier frequencies for
    vector variables (currents).

    Parameters
    ----------
    df_paired : pd.DataFrame
        Paired observation and model data with columns ['OBS', 'OFS',
        'SPD_BIAS', 'DIR_BIAS']
    name_var : str
        Variable name ('cu' for currents)
    prop : Any
        Properties object containing configuration parameters
    logger : Logger
        Logger instance for logging messages

    Returns
    -------
    List[Union[float, str]]
        List of skill metrics:
        [rmse, r_value, bias, bias_perc, bias_dir, cf, cfpf, pof, pofpf,
         nof, nofpf, stdev, X1]
        Where:
        - rmse: Root mean squared error of speed
        - r_value: Pearson correlation coefficient of speed
        - bias: Mean speed bias
        - bias_perc: Mean speed bias as percentage
        - bias_dir: Mean direction bias
        - cf: Central frequency (percentage within error threshold)
        - cfpf: Central frequency pass/fail ('pass' if >= 90%)
        - pof: Positive outlier frequency
        - pofpf: Positive outlier frequency pass/fail
        - nof: Negative outlier frequency
        - nofpf: Negative outlier frequency pass/fail
        - stdev: Standard deviation of speed bias
        - X1: Error threshold
    """
    datathreshold = 5

    # Get target error range
    X1, X2 = nos_metrics.get_error_threshold(
        'cu_dir', os.path.join(prop.path, 'conf', 'error_ranges.csv'))

    df_paired_ = df_paired.copy()
    df_paired = df_paired.dropna(subset=['OBS_DIR', 'OFS_DIR'])
    # Update obs and ofs after handling NaN
    obs = df_paired['OBS_DIR'].apply(lambda x: get_distance_angle(x, 0)).values
    ofs = df_paired['OFS_DIR'].apply(lambda x: get_distance_angle(x, 0)).values

    dir_bias = df_paired['DIR_BIAS']
    if np.nansum(~np.isnan(obs)) >= datathreshold:
        # RMSE
        rmse = nos_metrics.rmse(ofs, obs)
        rmse = np.around(rmse, decimals=2)

        # Pearson's R
        r_value = nos_metrics.pearson_r(ofs, obs)
        if math.isnan(r_value):
            logger.warning(
                '%s -- The correlation coefficient could not be calculated (i.e. R=NaN)',
                name_var)
        r_value = np.around(r_value, decimals=2)

        # Mean bias & bias percent
        bias = dir_bias.mean()
        bias_perc = np.nan
        bias = np.around(bias, decimals=2)
        bias_dir = dir_bias.mean()
        bias_dir = np.around(bias_dir, decimals=2)

        ######### DIR THRESHOLD STATS ##########
        # Central frequency
        # Not using X2 right now, only X1
        npbias = np.array(dir_bias)
        cf = nos_metrics.central_frequency(npbias, X1)
        cf = np.around(cf, decimals=2)

        # Positive/negative outlier frequency
        pof = nos_metrics.positive_outlier_freq(npbias, X1)
        pof = np.around(pof, decimals=2)
        nof = nos_metrics.negative_outlier_freq(npbias, X1)
        nof = np.around(nof, decimals=2)

        # MDPO/MDNO
        mdpo = nos_metrics.max_duration_positive_outliers(np.array(df_paired_['DIR_BIAS']), X1)
        mdno = nos_metrics.max_duration_negative_outliers(np.array(df_paired_['DIR_BIAS']), X1)
        diffs = np.asarray(df_paired['DateTime'].diff().dt.total_seconds() / 3600)
        dt = np.median(diffs)
        mdpo = mdpo * dt
        mdno = mdno * dt
        mdno = np.around(mdno, decimals=2)
        mdpo = np.around(mdpo, decimals=2)

        # Standard deviation or error/bias
        stdev = nos_metrics.standard_deviation(npbias)
        stdev = np.around(stdev, decimals=2)

        # Check criteria
        # Pass or fail?
        wof = None
        criteria = nos_metrics.check_nos_criteria(cf, pof, nof, mdpo, mdno, wof)
        cfpf = criteria['cf']
        pofpf = criteria['pof']
        nofpf = criteria['nof']
        mdpopf = criteria['mdpo']
        mdnopf = criteria['mdno']
        wofpf = criteria['wof']
    else:
        nodatatext = '<' + str(datathreshold) + ' data points'
        rmse = nodatatext
        r_value = nodatatext
        bias = nodatatext
        bias_perc = nodatatext
        bias_dir = nodatatext
        cf = nodatatext
        cfpf = nodatatext
        pof = nodatatext
        pofpf = nodatatext
        nof = nodatatext
        nofpf = nodatatext
        mdpo = nodatatext
        mdno = nodatatext
        mdpopf = nodatatext
        mdnopf = nodatatext
        wof = nodatatext
        wofpf = nodatatext
        stdev = nodatatext

    return [rmse,
            r_value,
            bias,
            bias_perc,
            bias_dir,
            cf,
            cfpf,
            pof,
            pofpf,
            nof,
            nofpf,
            mdpo,
            mdpopf,
            mdno,
            mdnopf,
            wof,
            wofpf,
            stdev,
            X1]

def skill_extrema(
    df_paired: pd.DataFrame,
    name_var: str,
    station_id: str,
    prop: Any,
    logger: Logger,
) -> list[Union[float, str]]:
    """
    Calculate skill metrics for water level extrema (HW/LW),
    including amplitude and timing metrics.
    """
    # X1 is the amplitude threshold, T1 is timing (usually 0.5h)
    X1, _ = nos_metrics.get_error_threshold(name_var, os.path.join(prop.path, 'conf', 'error_ranges.csv'))
    T1 = 0.5

    obs = df_paired['OBS']
    ofs = df_paired['OFS']
    bias = df_paired['BIAS']
    timing_err = df_paired['TIMING_ERR']

    # Amplitude Stats (Reuse standard scalar logic)
    rmse = nos_metrics.rmse(ofs, obs)
    cf = nos_metrics.central_frequency(bias, X1)
    pof = nos_metrics.positive_outlier_freq(bias, X1)
    nof = nos_metrics.negative_outlier_freq(bias, X1)

    # Timing Stats
    tcf = nos_metrics.timing_central_frequency(timing_err, T1)
    timing_rmse = np.sqrt(np.nanmean(timing_err**2))

    # Evaluate all criteria
    criteria = nos_metrics.check_nos_criteria(cf, pof, nof, 0, 0, None, tcf=tcf)

    # return [rmse,
    #         r_value,
    #         bias,
    #         bias_perc,
    #         bias_dir,
    #         cf,
    #         cfpf,
    #         pof,
    #         pofpf,
    #         nof,
    #         nofpf,
    #         mdpo,
    #         mdpopf,
    #         mdno,
    #         mdnopf,
    #         wof,
    #         wofpf,
    #         stdev,
    #         X1]

    return [
        np.around(rmse, 2),
        None,
        np.around(bias.mean(), 2),
        None,
        None,
        np.around(cf, 2),
        criteria['cf'],
        np.around(pof),
        criteria['pof'],
        np.around(nof),
        criteria['nof'],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        #np.around(tcf, 2),
        #criteria['tcf'],
        #np.around(timing_rmse, 2),
        X1
    ]
