name: ofs_dps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - ipykernel=6.29.3
  - numpy=1.26.4
  - matplotlib=3.8.4
  - cartopy=0.23.0
  - basemap=1.4.1
  - xarray=2024.5.0
  - netcdf4=1.6.5
  - geopandas=0.14.4
  - threddsclient=0.4.5
  - siphon=0.9
  - plotly=5.22.0
  - seaborn=0.13.2
  - regionmask=0.12.1
  - boto3=1.34.113
  - dask=2024.5.1
  - basemap-data-hires=1.3.2
  - pylint=3.3.1
  - intake=2.0.7
  - conda-forge::intake-xarray=2.0.0
  - pyinterp=2024.11.0